---
title: ''
output: 
    #pdf_document: 
    bookdown::word_document2: 
      reference_docx: word-styles-reference.docx #make sure this line is indented! see this guide for formatting: https://rmarkdown.rstudio.com/articles_docx.html
bibliography: references.bib
csl: new-phytologist.csl
nocite: |
  @martinez-sancho_drought_2022



---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\raggedright

**Title:** What drives forest carbon storage? The ramifications of source-sink decoupling

**Authors:** 

Kristina J. Anderson-Teixeira^1,2^* (Orcid ID : 0000-0001-8461-9713)

Steven A. Kannenberg^3^ (ORCID: 0000-0002-4097-9140)




**Author Affiliations:**

1. Conservation Ecology Center; Smithsonian National Zoo & Conservation Biology Institute; Front Royal, Virginia 22630, USA

2. Forest Global Earth Observatory; Smithsonian Tropical Research Institute; Panama, Republic of Panama

3. Department of Biology, Colorado State University, Fort Collins, Colorado 80523, USA


*corresponding author: teixeirak@si.edu; +1 540 635 6546


**keywords:** *(5-8)* <!--5-8 keywords. Should be given after references, but .Rmd can't do that.-->

**quote:** the preponderance of evidence demonstrates that forest CO~2~ uptake and sequestration are decoupled on time scales ranging from seconds to years



| | count |
|--|--|
|words|  1454 *(1500 max)* | <!--1200– 1500 words (~6-10 par) -->
|figures|  *(1-2 encouraged)* | <!--encouraged to use one or two figures (or tables/ boxes) in addition to help the explanation or simply to illustrate the general area-->
|tables| 0 |
|references | 13 *(15 max)* | <!--max 15-->



\newpage
<!--The highlighted article should be cited in the first paragraph in the style ‘In this issue of New Phytologist, Smith et al. (pp. 000-000) ...’.-->
As the climate changes and scientists seek to project its future course, an important uncertainty lies in the response of forests. 
Will rising atmospheric carbon dioxide (CO~2~) and lengthening growing seasons relieve limitations to tree growth, allowing increased carbon (C) sequestration in long-lived woody tissues and providing a negative feedback to climate change?
Or will increasing heat and drought stress reduce growth and increase mortality, resulting in a positive feedback to climate change?
To answer this question, global C cycle models simulate photosynthesis under future conditions, using simple plant C allocation schemes to estimate the amount of C sequestered in woody growth versus that allocated to short-lived pools that are more rapidly respired back to the atmosphere as CO~2~ [@fatichi_moving_2014]. 
Yet, there is growing evidence that these schemes are too simplistic, as wood production is frequently decoupled from photosynthesis [@delpierre_wood_2016; @etzold_number_2022], either through passive limitation of woody tree growth by environmental conditions or active allocation prioritizing other sinks.
Needed, then, is an understanding of how woody growth is jointly shaped by photosynthesis (i.e., source limitation) and demand from various C sinks (i.e., sink limitation) across species and biomes [@korner_paradigm_2015]. 
In this issue of *New Phytologist*, Martinez-Sancho *et al.* (pp. 000-000) exemplifies the type of research needed to improve our ability to predict forest C sequestration under climate change, using an innovative approach to describe the seasonal course of C sequestration in tree stem growth and how it is affected by drought.

Characterizing the seasonal course of woody growth is challenging, even with frequent dendrometer measurements, because stems shrink and swell in relation to their hydraulic status, and because C sequestration associated with cell wall thickening lags behind radial growth [@cuny_woody_2015; @martinez-sancho_drought_2022].
To understand the timing of C sequestration, @martinez-sancho_drought_2022 collected weekly microcores from mature *Picea abies* trees to characterize the seasonal timing of wood formation, and then combined this information with a detailed analysis of wood anatomy and C stable isotopes (∂^13^C). <!--following methods pioneered by @cuny_generalized_2013, @perez-de-lis_cutting_2022, @cuny_woody_2015--> 
In a non-drought year (2014), the rate of cell expansion peaked at the end of June, while rates of cell wall thickening and C sequestration peaked in early July, with all three variables displaying a unimodal peak. 
These patterns were consistent with other studies showing that tree stem growth rate peaks near the time of the summer solstice, with C sequestration lagging stem radial expansion [@etzold_number_2022;@dow_warm_inpress;@cuny_woody_2015].

<!--drought impacts-->
Extreme summer drought in 2015 resulted in dramatically different seasonal patterns of woody growth and C sequestration [**Fig. 1**, @martinez-sancho_drought_2022]. 
During a 41-day period from mid-June to late July during which stem radial shrinkage indicated physiological water stress, rates of cell enlargement and thickening were slowed, resulting in bimodal growth and C sequestration curves with peaks before and after the drought. 
Overall, C sequestration was reduced 67% during the drought period.
Meanwhile, ∂^13^C isotopes indicated increased C isotope discrimination, indicative of water limitation resulting in higher intrinsic water use efficiency during the drought. 
The ∂^13^C drought signature appeared in wood formed after the drought, suggesting that while sink limitations prevented the C fixed during the drought from contributing immediately to woody growth, this C was reserved and used to accelerate growth after the drought. 
Indeed, higher compensatory growth and C sequestration rates after the drought resulted in similar total C sequestration during the drought and reference years [@martinez-sancho_drought_2022].
Thus, study of intraannual dynamics of wood formation revealed a drought impact on growth that would have gone undetected at the annual scale.

![**Figure 1. Schematic summarizing the effects of a severe summer drought on seasonal patterns in CO~2~ uptake (photosynthesis) and C sequestration (woody growth).** Based on @martinez-sancho_drought_2022, which combined weekly microcores with a detailed analysis of wood anatomy and C stable isotopes (∂^13^C) to understand the seasonal dynamics of C sequestration in four mature *Picea abies* trees in a Swiss valley. Strong reductions in stem growth during the drought resulted in nonstructural carbohydrates (NSC) stores that were used in a compensatory growth response following the drought, resulting in similar C sequestration in drought and non-drought years.](display/Figure1.png)

The fact that a severe drought coinciding with peak growing season had little effect on annual C sequestration is somewhat surprising in the context of other studies. 
Typically, annual growth is quite responsive to drought or temperature stress during the peak season for woody growth [@dow_warm_inpress; @dorangeville_drought_2018; @kannenberg_droughtinduced_2022]. 
This is because cellular enlargement requires adequate turgor pressure and is therefore particularly sensitive to aridity [@delpierre_wood_2016;@etzold_number_2022; @zweifel_why_2021; @kannenberg_droughtinduced_2022].
In the @martinez-sancho_drought_2022 study, a strong start to growth prior to the drought and strong post-drought compensatory response resulted in normal annual woody productivity.
This was made possible by the relatively short duration of the drought; while short severe droughts can significantly impact annual growth, growth tends to be more sensitive to longer droughts [@dorangeville_drought_2018].
The findings of @martinez-sancho_drought_2022 point to the importance of the timing and length of drought in shaping C sequestration and highlight the need for improved understanding of the seasonal dynamics of CO~2~ uptake and woody growth, including their decoupling. 

The @martinez-sancho_drought_2022 study adds to growing evidence that CO~2~ uptake and woody production are decoupled across a range of time scales (**Fig. 2**).
On time scales of seconds to hours, photosynthesis and stem growth are completely decoupled, with photosynthesis occurring during the day and most stem radial expansion occurring at night when stem hydration is maximal [@zweifel_why_2021].
On time scales of days to months, stem growth is influenced by photosynthate availability, but is strongly constrained by temperature and soil moisture [@delpierre_wood_2016;@etzold_number_2022], being more sensitive to drought than *GPP* [@kannenberg_droughtinduced_2022].
On an annual time scale, woody aboveground net primary productivity (*ANPP~woody~*) and *GPP* can be completely uncorrelated [e.g., @delpierre_wood_2016], implying significant annual variability in C allocation to woody growth versus other sinks (e.g., non-woody tissues, reproduction, respiration, root exudation, non-structural carbohydrate pools).
In a cross-biome synthesis of available data, tree-ring widths were on average only weakly correlated with *GPP* [r ≤ 0.38, @cabon_crossbiome_2022]. <!--, generally with strongest correlation for time windows covering all or part of the period between the summer solstices of the previous and current years-->
The observed strong decoupling of *GPP* and annual *ANPP~woody~* implies that global change drivers will have different impacts on CO~2~ uptake and carbon sequestration.
For instance, while warm springs increase *GPP* in temperate deciduous forests, this does not translate into increased stem growth [@dow_warm_inpress].
Thus, **the preponderance of evidence demonstrates that forest CO~2~ uptake and sequestration are decoupled on time scales ranging from seconds to years**. <!--this is our highlighted quote --need to modify on cover page if changed here.-->

![**Figure 2. Schematic summarizing sources of decoupling between CO~2~ uptake and C sequestration across various time scales.** Across scales, various processes (text boxes) decouple C sequestration (wood formation or woody productivity, *ANPP~woody~*, on the ecosystems scale) from CO~2~ uptake (photosynthesis or gross primary productivity, *GPP*, on the ecosystems scale). Shaded wedges indicate integration across time and space. Tree ring images courtesy of Elisabet Martínez-Sancho (close-up of annual ring) and Steven A. Kannenberg (annual rings). Watercolor paintings by Kristina J. Anderson-Teixeira.](display/figure2.png)

An important open question is the extent to which *ANPP~woody~* and *GPP* are coupled on decadal to centennial time scales, and by extension how global change drivers that alter *GPP* will affect *ANPP~woody~*.
Across broad climatic gradients where trees are largely adapted and acclimated to differences in climate, *GPP* and *ANPP~woody~* vary roughly in proportion to one another [@banburymorgan_global_2021].
However, these processes may respond differently to global change drivers.
While sustained decreases in *GPP* will inevitably decrease *ANPP~woody~*, it remains unclear whether sustained *increases* in *GPP* will result in the corresponding increases in *ANPP~woody~*. 
When *GPP* increased in response to four years of experimental CO~2~ fertilization of a mature eucalypt forest, *ANPP~woody~* remained unchanged, with the majority of extra C being allocated belowground and rapidly respired back to the atmosphere [@jiang_fate_2020].
Additional studies of C allocation under altered environmental conditions are needed to understand the long-term coupling of *GPP* and *ANPP~woody~*, and by extension how climate change will impact forest C sequestration.

The decoupling of *ANPP~woody~* from *GPP* has important implications for our understanding of forest C sequestration under a changing climate.
This is particularly true because decoupling is likely to increase in the future as it is driven, in part, by temperature and water stress.
Most global C cycle models represent C allocation to *ANPP~woody~* as a constant fraction of *GPP* [@friend_need_2019], and thereby effectively assume that long-term C sequestration in woody growth -- the main variable of interest for climate change projections -- parallels *GPP*.
Yet, as reviewed above, this assumption is not accurate, with the implication that models may over- or under-predict forest sensitivity to global change drivers.
For instance, models would be likely to overestimate the sensitivity of *ANPP~woody~* to relatively short droughts [e.g., @martinez-sancho_drought_2022] but underestimate its sensitivity to longer droughts [@kannenberg_droughtinduced_2022], while overestimating *ANPP~woody~* of temperate deciduous forests under warming spring temperatures [@dow_warm_inpress].
To reduce uncertainty regarding the future impact of global change on forest C sequestration, we need to develop comprehensive understanding regarding: 1) when, where, and why decoupling occurs, 2) the spatial and temporal scales at which it operates, and 3) the implications for how we understand and model the forest C cycle. 
Given the complexity of tree physiology and forest C cycling, answering these open questions necessitates cross-scale and cross-methodology approaches, spanning from wood formation [@martinez-sancho_drought_2022] to dendroecology, eddy covariance, and modeling. 


\newpage

# References {-#References}
<!--The highlighted article should be included in the References section (the page numbers should be listed as 000–000).-->



